# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Build Library

on:
  workflow_call:
    inputs:
      build-dir:
        required: true
        type: string
      dist-dir:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]

    steps:
    - uses: actions/checkout@v3

    - name: Configure Static Library Build
      run: >
        cmake -B ${{ inputs.build-dir }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DBUILD_SHARED_LIBS=OFF
        -S ${{ github.workspace }}

    - name: Build Static Library
      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      run: cmake --build ${{ inputs.build-dir }} --config ${{ matrix.build_type }}

    - name: Install Static Library
      run: cmake --install ${{ inputs.build-dir }} --prefix ${{ inputs.install-dir }} 
